### ISSUE TITLE
CurseGradle maven change

### ISSUE THREAD

**Issue by hypherionmc** [NerjalNosk/Conditional_keep_inventory#12]
Hi there :)

Just wanted to inform you that the maven for cursegradle has changed from `https://maven.explodingcreeper.me` to `https://maven.explodingcreeper.me/releases`

**Comment by NerjalNosk** [comment]
Oh
Thanks I guess?
Although I am not planning on using CurseGradle in the end, as if I really was to make new publications at every builds, CF would quickly ban me for files flooding :sweat_smile:
